apiVersion: apps/v1
kind: Deployment
metadata:
  name: javawebappdeploy      
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: javaweb      
  strategy:
    type: RollingUpdate
    rollingUpdate:
       maxSurge: 1
       maxUnavailable: 1
  minReadySeconds: 15                 
  template:
    metadata:
      name: javapod
      labels:
        app: javaweb      
    spec:
      containers:      
      - name: javawebappcontainer
        image: vishnuvel/java-web-docker:25
        ports:
        - containerPort: 8080        
        volumeMounts:  
        - name: javavol
          mountPath: "/home/ubuntu"
      volumes:
      - name: javavol          
        hostPath:
          path: "/./"       
---
apiVersion: v1
kind: Service
metadata: 
  name: javasvc
spec:
  type: NodePort       
  selector:
    app: javaweb     
  ports:
  - port: 8080
    targetPort: 8080    
          



