apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongodeploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mongo      
  template:
    metadata:      
      name: mongopod
      labels:
        app: mongo      
    spec:
      containers:
      - name: mongocontainer        
        image: mongo
        ports:
        - containerPort: 27017
        env:   
        - name: MONGO_INITDB_ROOT_USERNAME
          value: vishnu
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: Vishnu@347
        volumeMounts:
        - name: mongovol
          mountPath: /data/db
      volumes:
      - name: mongovol        
        persistentVolumeClaim:
          claimName: mongopvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongosvc      
spec:
  type: ClusterIP      
  selector:
    app: mongo      
  ports:
  - port: 27017        
    targetPort: 27017

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
   name: mongopvc    
   accessModes:
   - ReadWriteMany
     resources:
       requests:
         storage: 100mi
