apiVersion: apps/v1
kind: ReplicaSet
metadata: 
  name: javars     
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: java        
  template:
    metadata:
      labels:
        app: java      
    spec:
      containers:      
      - name: javapod      
        image: vishnuvel/maven-web-app:2
        ports:             
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
   name: java
spec:
  type: ClusterIP  
  selector:
    app: java
  ports:
  - port: 80        
    targetPort: 8080


