apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopv      
spec:
  accessModes:
    - ReadWriteMany        
  capacity:
    storage: 200Mi      
  hostPath:
    path: "/home/ubuntu/mongodb"      
