apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongopvnfsstorage      
spec:   
  capacity:       
    storage: 200Mi      
  accessModes:  
    - ReadWriteMany
  nfs:
    server: 172.31.5.151      
    path: "/mnt/nfs_share"


