apiVersion: apps/v1
kind: Deployment
metadata:
  name: springappdeploy
spec:
  replicas: 2      
  selector:
    matchLabels:
      app: spring      
  template:
    metadata:
      name: springpod
      labels:
        app: spring      
    spec:
      containers:
      - name: springcont        
        image: vishnuvel/spring-boot-mongo
        ports:
        - containerPort: 8080        
        env:
          - name: MONGO_DB_HOSTNAME
            value: mongosvc
          - name: MONGO_DB_USERNAME
            value: vishnu
          - name: MONGO_DB_PASSWORD
            value: Vishnu@347

---
apiVersion: v1
kind: Service
metadata: 
  name: springsvc
spec:
  type: NodePort      
  selector:
    app: spring      
  ports:
  -  port: 27017
     targetPort: 8080



