apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefullmongo      
spec:
  replicas: 2      
  selector:
    matchLabels:      
      app: mongo
  serviceName: "mongo"    
  template:
    metadata:
      name: mongopod      
      labels:
        app: mongo    
    spec:
      terminationGracePeriodSeconds: 10       
      containers:
      - name: mongocontainer      
        image: mongo
        ports:
          - containerPort: 27017        
        env:  
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              configMapKeyRef:
                name: spring
                key: mongodbusername
          - name: MONGO_INITDB_ROOT_PASSWORD 
            valueFrom:
              secretKeyRef:
                name: secrete            
                key: password
        volumeMounts:                
          - name: mongovol      
            mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: mongovol
      spec:
        storageClassName: "nfs-storageclass"
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 1Gi       
---
apiVersion: v1
kind: Service
metadata: 
  name: mongosvc    
spec:
  clusterIP: None      
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017    
---
apiVersion: apps/v1
kind: Deployment
metadata:
   name: springapp     
spec:
  replicas: 2      
  #strategy:
  # type: RollingUpdate
  # rollingUpdate:
  #   maxSurge: 1
  #   maxUnavailable: 1
  # minReadySeconds: 30
  selector:
    matchLabels:
      app: springapp        
  template:
    metadata:      
      name: springpod
      labels:
        app: springapp      
    spec:
      containers:
      - name: springappcontainer        
        image: vishnuvel/spring-boot-mongo:25
        ports:
          - containerPort: 8080        
        env:
          - name:  MONGO_DB_USERNAME
            valueFrom:
              configMapKeyRef:
                name: spring
                key: mongodbusername         
          - name:  MONGO_DB_HOSTNAME
            value: mongosvc
          - name: MONGO_DB_PASSWORD
            valueFrom:
              secretKeyRef:      
                name: secrete
                key: password
---
apiVersion: v1
kind: Service
metadata:
  name: springappsvc
spec:
  type: NodePort
  selector:
     app: springapp      
  ports:
  - port: 8080        
    targetPort: 8080
